"""Added suspension_reason to User table

Revision ID: 062552be22e0
Revises: 79186402554e
Create Date: 2026-05-02 19:56:31.655393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062552be22e0'
down_revision = '79186402554e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspension_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('suspension_reason')

    # ### end Alembic commands ###
