"""Increase registration number length to 50

Revision ID: 505cbdfe0c16
Revises: 062552be22e0
Create Date: 2026-05-02 20:29:36.086522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505cbdfe0c16'
down_revision = '062552be22e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('registration_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=17),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('registration_number',
               existing_type=sa.String(length=17),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###
