"""Initial migration

Revision ID: 5d4c1ab06a1f
Revises: 
Create Date: 2026-05-01 17:29:19.529839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4c1ab06a1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_cycle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinator_year2_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('coordinator_year4_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'coordinator', ['coordinator_year4_id'], ['coordinator_id'])
        batch_op.create_foreign_key(None, 'coordinator', ['coordinator_year2_id'], ['coordinator_id'])

    with op.batch_alter_table('milestone', schema=None) as batch_op:
        batch_op.alter_column('cycle_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('panel', schema=None) as batch_op:
        batch_op.alter_column('cycle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('panel_coordinator_id_fkey'), type_='foreignkey')
        batch_op.drop_column('coordinator_id')

    with op.batch_alter_table('project_pitch', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_student_supervisor_pitch', ['student_id', 'supervisor_id'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('student_assigned_panel_id_fkey'), type_='foreignkey')
        batch_op.drop_column('assigned_panel_id')

    with op.batch_alter_table('student_submission', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_student_milestone', ['student_id', 'milestone_id'])

    with op.batch_alter_table('supervisor', schema=None) as batch_op:
        batch_op.drop_column('research_interests')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('research_interests', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('student_submission', schema=None) as batch_op:
        batch_op.drop_constraint('unique_student_milestone', type_='unique')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_panel_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('student_assigned_panel_id_fkey'), 'panel', ['assigned_panel_id'], ['panel_id'])

    with op.batch_alter_table('project_pitch', schema=None) as batch_op:
        batch_op.drop_constraint('unique_student_supervisor_pitch', type_='unique')

    with op.batch_alter_table('panel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinator_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('panel_coordinator_id_fkey'), 'coordinator', ['coordinator_id'], ['coordinator_id'])
        batch_op.alter_column('cycle_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('milestone', schema=None) as batch_op:
        batch_op.alter_column('cycle_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('academic_cycle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('coordinator_year4_id')
        batch_op.drop_column('coordinator_year2_id')

    # ### end Alembic commands ###
