"""Add coordinator history table

Revision ID: 633f06a5cc15
Revises: 505cbdfe0c16
Create Date: 2026-05-02 21:03:33.695586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633f06a5cc15'
down_revision = '505cbdfe0c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordinator_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Enum('2', '4', name='history_year_enum'), nullable=False),
    sa.Column('previous_coordinator_name', sa.String(length=150), nullable=False),
    sa.Column('current_coordinator_name', sa.String(length=150), nullable=False),
    sa.Column('reassignment_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coordinator_history')
    # ### end Alembic commands ###
