"""Added account deletion logs

Revision ID: 79186402554e
Revises: 5d4c1ab06a1f
Create Date: 2026-05-01 19:34:50.965520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79186402554e'
down_revision = '5d4c1ab06a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_deletion_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('deleted_user_email', sa.String(length=100), nullable=False),
    sa.Column('deletion_reason', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_deletion_log')
    # ### end Alembic commands ###
