"""Clean database rebuild

Revision ID: ca1f498a5344
Revises: 
Create Date: 2026-05-18 10:00:12.601915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1f498a5344'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordinator_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Enum('2', '4', name='history_year_enum'), nullable=False),
    sa.Column('previous_coordinator_name', sa.String(length=150), nullable=False),
    sa.Column('current_coordinator_name', sa.String(length=150), nullable=False),
    sa.Column('reassignment_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('research_tag',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('tag_name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=25), nullable=False),
    sa.Column('last_name', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=13), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('user_role', sa.Enum('Student', 'Supervisor', 'Administrator', 'Coordinator', name='role_types'), nullable=False),
    sa.Column('account_status', sa.Enum('Pending', 'Accepted', 'Suspended', name='status_types'), nullable=False),
    sa.Column('suspension_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('account_deletion_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('deleted_user_email', sa.String(length=100), nullable=False),
    sa.Column('deletion_reason', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('supervisor',
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('max_2nd_year_capacity', sa.Integer(), nullable=False),
    sa.Column('max_4th_year_capacity', sa.Integer(), nullable=False),
    sa.Column('office_location', sa.String(length=100), nullable=True),
    sa.Column('office_hours', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('supervision_preference', sa.Text(), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('supervisor_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('upload_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('upload_type', sa.Enum('Supervisors_CSV', '2nd Year CSV', '4th Year CSV', name='csv_upload_type'), nullable=False),
    sa.Column('year', sa.Enum('2', '4', name='upload_year'), nullable=True),
    sa.Column('status', sa.Enum('Success', 'Partial', 'Fail', name='upload_status'), nullable=False),
    sa.Column('records_added', sa.Integer(), nullable=False),
    sa.Column('error_report', sa.JSON(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('coordinator',
    sa.Column('coordinator_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Enum('2', '4', name='coordinator_year'), nullable=False),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisor.supervisor_id'], ),
    sa.PrimaryKeyConstraint('coordinator_id'),
    sa.UniqueConstraint('supervisor_id')
    )
    op.create_table('supervisor_interest',
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisor.supervisor_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['research_tag.tag_id'], ),
    sa.PrimaryKeyConstraint('supervisor_id', 'tag_id')
    )
    op.create_table('academic_cycle',
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('coordinator_year2_id', sa.Integer(), nullable=True),
    sa.Column('coordinator_year4_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coordinator_year2_id'], ['coordinator.coordinator_id'], ),
    sa.ForeignKeyConstraint(['coordinator_year4_id'], ['coordinator.coordinator_id'], ),
    sa.PrimaryKeyConstraint('cycle_id')
    )
    op.create_table('broadcast',
    sa.Column('broadcast_id', sa.Integer(), nullable=False),
    sa.Column('coordinator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(length=255), nullable=True),
    sa.Column('broadcast_year', sa.Enum('2', '4', name='broadcast_year'), nullable=False),
    sa.ForeignKeyConstraint(['coordinator_id'], ['coordinator.coordinator_id'], ),
    sa.PrimaryKeyConstraint('broadcast_id')
    )
    op.create_table('milestone',
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('milestone_name', sa.String(length=50), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Enum('2', '4', name='year_milestone_levels'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['academic_cycle.cycle_id'], ),
    sa.PrimaryKeyConstraint('milestone_id')
    )
    op.create_table('panel',
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('panel_number', sa.String(length=5), nullable=False),
    sa.Column('year', sa.Enum('2', '4', name='panel_year'), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['academic_cycle.cycle_id'], ),
    sa.PrimaryKeyConstraint('panel_id')
    )
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('assigned_supervisor_id', sa.Integer(), nullable=True),
    sa.Column('registration_number', sa.String(length=17), nullable=False),
    sa.Column('year', sa.Enum('2', '4', name='year_levels'), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_supervisor_id'], ['supervisor.supervisor_id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['academic_cycle.cycle_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('panel_member',
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('panel_role', sa.Enum('Chair', 'Member', name='panel_roles'), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['panel.panel_id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisor.supervisor_id'], ),
    sa.PrimaryKeyConstraint('panel_id', 'supervisor_id')
    )
    op.create_table('project_pitch',
    sa.Column('pitch_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('project_title', sa.String(length=255), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Accepted', 'Declined', name='pitch_status'), nullable=False),
    sa.Column('decline_reason', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisor.supervisor_id'], ),
    sa.PrimaryKeyConstraint('pitch_id'),
    sa.UniqueConstraint('student_id', 'supervisor_id', name='unique_student_supervisor_pitch')
    )
    op.create_table('student_submission',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('submission_at', sa.DateTime(), nullable=True),
    sa.Column('submission_status', sa.Enum('On Time', 'Late', 'Resubmitted', name='submission_status'), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.milestone_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('submission_id'),
    sa.UniqueConstraint('student_id', 'milestone_id', name='unique_student_milestone')
    )
    op.create_table('submission_attachment',
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=250), nullable=False),
    sa.Column('file_type', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['student_submission.submission_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission_attachment')
    op.drop_table('student_submission')
    op.drop_table('project_pitch')
    op.drop_table('panel_member')
    op.drop_table('student')
    op.drop_table('panel')
    op.drop_table('milestone')
    op.drop_table('broadcast')
    op.drop_table('academic_cycle')
    op.drop_table('supervisor_interest')
    op.drop_table('coordinator')
    op.drop_table('upload_log')
    op.drop_table('supervisor')
    op.drop_table('account_deletion_log')
    op.drop_table('user')
    op.drop_table('research_tag')
    op.drop_table('coordinator_history')
    # ### end Alembic commands ###
