"""add supervisor onboarding fields

Revision ID: e5950eb9fb99
Revises: 633f06a5cc15
Create Date: 2026-05-13 12:12:33.568510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5950eb9fb99'
down_revision = '633f06a5cc15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('office_location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('office_hours', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('onboarding_complete', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor', schema=None) as batch_op:
        batch_op.drop_column('onboarding_complete')
        batch_op.drop_column('bio')
        batch_op.drop_column('office_hours')
        batch_op.drop_column('office_location')

    # ### end Alembic commands ###
