"""add student onboarding flag

Revision ID: e6552ce7196d
Revises: e5950eb9fb99
Create Date: 2026-05-14 07:24:25.028953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6552ce7196d'
down_revision = 'e5950eb9fb99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        # Add server_default='false' 
        batch_op.add_column(sa.Column('onboarding_complete', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('onboarding_complete')

    # ### end Alembic commands ###
